name: kustomize deploy and verify
description: kustomize
author: yyj

inputs:
  name:
    description: deployment name
    required: true

  namespace:
    description: k8s namespace
    required: true

  image:
    description: image name
    required: true

  kube_config:
    description: kube config
    required: true

  context:
    description: TKE context name
    required: true

  directory:
    description: kustomize directory
    required: true

runs:
  using: composite
  steps:
    - name: pull kube config
      run: echo "${{ inputs.kube_config }}" > ${{ github.workspace }}/kc
      shell: bash

    - name: switch to TKE context
      run: |
        kubectl --kubeconfig=${{ github.workspace }}/kc config get-contexts
        kubectl --kubeconfig=${{ github.workspace }}/kc config use-context ${{ inputs.context }}
      shell: bash

    - name: deploy
      run: |
        cd ${{ inputs.directory }}
        kustomize edit set image ${{ inputs.image }}
        kubectl --kubeconfig=${{ github.workspace }}/kc apply -n ${{ inputs.namespace }} -k ${{ inputs.directory }}
      shell: bash

    - name: verify
      run: kubectl --kubeconfig=${{ github.workspace }}/kc rollout status deployment/${{ inputs.name }} -n ${{ inputs.namespace }}
      shell: bash

    - name: clear
      if: always()
      run: rm -rf ${{ github.workspace }}/kc
      shell: bash


