name: kustomize
description: kustomize
author: yyj

inputs:
  image_name:
    description: image name
    required: true

  kube_config:
    description: kube config
    required: true

  kustomize_dir :
    description: kustomize directory
    required: true


runs:
  using: composite
  steps:
    - name: pull kubeconfig
      run: |
        mkdir -p ${{ github.workspace }}/kubeconf
        echo "${{ inputs.kube_config }}" > ${{ github.workspace }}/kubeconf/config
        export KUBECONFIG=${{ github.workspace }}/kubeconf/config
      shell: bash 



    - name: kustomize
      run: |
        kustomize edit set image ${{ inputs.image_name }}
        kustomize build ${{ inputs.kustomize_dir }} |tee install.yml
        cat install.yml
        echo '------'
        ls
      shell: bash 
