name: kustomize
description: kustomize
author: yyj

inputs:
  image:
    description: image name
    required: true

  kube_config:
    description: kube config
    required: true

  context:
    description: context name
    required: true

  directory:
    default: ${{ github.workspace }}/ci



runs:
  using: composite
  steps:
    - name: ba
      run: |
        mkdir -p ${{ github.workspace }}/kubeconf
        echo "${{ inputs.kube_config }}" > ${{ github.workspace }}/kubeconf/config
        export KUBECONFIG=${{ github.workspace }}/kubeconf/config

        kubectl config use-context ${{ inputs.context }}
             

        sed -i "s/cicd-test/${{ env.APP_NAME }}/g" ${{ inputs.directory }}/*
        
        kustomize edit set image ${{ inputs.image }}
        kustomize build ${{ inputs.directory }} |tee install.yml
        
        cat install.yml
      shell: bash



