name: kustomize
description: kustomize
author: yyj

inputs:
  image:
    description: 123
    required: true

  kube_config:
    description: 123
    required: true


runs:
  using: composite
  steps:
    - name: pull kubeconfig
      run: |
        mkdir -p ${{ github.workspace }}/kubeconf
        echo "${{ inputs.kube_config }}" > ${{ github.workspace }}/kubeconf/config
        export KUBECONFIG=${{ github.workspace }}/kubeconf/config
      shell: bash 


    - name: replace yaml
      run: |
        sed -i "s/cicd-test/${{ env.APP_NAME }}/g" ${{ github.workspace }}/ci/*
      shell: bash 


    - name: kustomize
      run: |
        kustomize edit set image ${{ inputs.image }}
        kustomize build ${{ github.workspace }}/ci |tee install.yml
        cat install.yml
        echo '------'
        ls
      shell: bash 
