name: kustomize
description: kustomize
author: yyj

inputs:
  name:
    description: deployment name
    default: ${{ env.APP_NAME }}

  namespace:
    description: k8s namespace
    default: ${{ env.NAMESPACE }}

  image:
    description: image name
    required: true

  kube_config:
    description: kube config
    required: true

  context:
    description: TKE context name
    required: true

  directory:
    description: kustomize directory
    default: ${{ github.workspace }}/ci

runs:
  using: composite
  steps:
    - name: pull kube config
      run: |
        mkdir -p ${{ github.workspace }}/kubeconf
        echo "${{ inputs.kube_config }}" > ${{ github.workspace }}/kubeconf/config
        export KUBECONFIG=${{ github.workspace }}/kubeconf/config
      shell: bash

    - name: switch to TKE context
      run: kubectl config use-context ${{ inputs.context }}
      shell: bash

    - name: deploy
      run: |
        cd ${{ inputs.directory }}
        kustomize edit set image ${{ inputs.image }}
        kubectl apply -n ${{ inputs.namespace }} -k ${{ inputs.directory }}
      shell: bash

    - name: verify
      run: |
        kubectl rollout status deployment/${{ inputs.name }} -n ${{ inputs.namespace }}
      shell: bash

    - name: clear
      if: always()
      run: |
        rm -rf ${{ github.workspace }}/kubeconf
      shell: bash


