name: kustomize
description: kustomize
author: yyj

inputs:
  image:
    description: image name
    required: true

  kube_config:
    description: kube config
    required: true





runs:
  using: composite
  steps:
    - name: ba
      run: |
        mkdir -p ${{ github.workspace }}/kubeconf
        echo "${{ inputs.kube_config }}" > ${{ github.workspace }}/kubeconf/config
        export KUBECONFIG=${{ github.workspace }}/kubeconf/config
        kubectl config use-context cls-22fbpa6r-100000669790-context-default
             

        cd ci
        sed -i "s/cicd-test/${{ env.APP_NAME }}/g" ${{ github.workspace }}/ci/*
        
        kustomize edit set image ${{ inputs.image }}
        kustomize build ${{ github.workspace }}/ci |tee install.yml
        
        cat install.yml
      shell: bash



